### ISSUE TITLE
shenyu-admin module test coverage improvement

### ISSUE THREAD

**Issue by 0x12FD16B** [apache/incubator-shenyu#1824]
## Task

improve shenyu-admin module test coverage, each line has record a class and the current test coverage is in the brackets, we hope to improve test coverage to above 85%.

Task List:
- [ ] following classes test code coverage @JooKS-me 
org.apache.shenyu.admin.service.impl.DataPermissionServiceImpl(0%)
org.apache.shenyu.admin.service.impl.SelectorServiceImpl(46%)
org.apache.shenyu.admin.service.impl.UpstreamCheckService(60%)
org.apache.shenyu.admin.service.impl.DashboardUserServiceImpl(66%)
org.apache.shenyu.admin.service.impl.RuleServiceImpl(75%)
org.apache.shenyu.admin.service.impl.MetaDataServiceImpl(81%)
org.apache.shenyu.admin.service.impl.PermissionServiceImpl(62%)

- [ ] following classes test code coverage @ttttangzhen 
org.apache.shenyu.admin.listener.http.HttpLongPollingDataChangedListener(7%) 
org.apache.shenyu.admin.listener.http.HttpLongPollingDataChangedListener.LongPollingClient(0%)
org.apache.shenyu.admin.listener.http.HttpLongPollingDataChangedListener.DataChangeTask(0%)

- [ ] following classes test code coverage
org.apache.shenyu.admin.service.register.ShenyuClientRegisterSpringCloudServiceImpl(6%)
org.apache.shenyu.admin.service.register.AbstractShenyuClientRegisterServiceImpl.AbstractShenyuClientRegisterServiceImpl(1%)
org.apache.shenyu.admin.service.register.ShenyuClientRegisterSpringMVCServiceImpl(9%)
org.apache.shenyu.admin.service.register.ShenyuClientRegisterSofaServiceImpl(14%)
org.apache.shenyu.admin.service.register.ShenyuClientRegisterDubboServiceImpl(17%)
org.apache.shenyu.admin.service.register.ShenyuClientRegisterTarsServiceImpl(15%)
org.apache.shenyu.admin.service.register.ShenyuClientRegisterDefaultServiceImpl(14%)
org.apache.shenyu.admin.service.register.ShenyuClientRegisterMotanServiceImpl(18%)
org.apache.shenyu.admin.service.register.ShenyuClientRegisterGrpcServiceImpl(18%)

- [ ] #1849 @Technoboy- 
org.apache.shenyu.admin.listener.AbstractDataChangedListener(3%)
org.apache.shenyu.admin.listener.ConfigDataCache(0%)
org.apache.shenyu.admin.listener.zookeeper.HttpServiceDiscovery(7%)
org.apache.shenyu.admin.listener.websocket.WebsocketListener(10%)
org.apache.shenyu.admin.listener.websocket.WebsocketConfigurator(28%)
org.apache.shenyu.admin.exception.ExceptionHandlers(18%)
org.apache.shenyu.admin.config.LdapConfiguration(0%)
org.apache.shenyu.admin.config.DataSyncConfiguration(0%)
org.apache.shenyu.admin.config.ConsulServerConfiguration(0%)
org.apache.shenyu.admin.config.DataBaseConfiguration(0%)

- [ ] following classes test code coverage
org.apache.shenyu.admin.shiro.bean.StatelessAuthFilter(6%)
org.apache.shenyu.admin.shiro.bean.StatelessToken(0%)
org.apache.shenyu.admin.shiro.config.ShiroRealm(0%)
org.apache.shenyu.admin.disruptor.subscriber.URIRegisterExecutorSubscriber(12%)
org.apache.shenyu.admin.disruptor.subscriber.MetadataExecutorSubscriber(60%)
org.apache.shenyu.admin.aspect.DataPermissionAspect(8%)

Please read the [Contribution Guideline](https://shenyu.apache.org/community/contributor/) before submitting the PR

**Comment by JooKS-me** [comment]
I would like to take:

- [ ]  org.apache.shenyu.admin.service.impl.DataPermissionServiceImpl(0%)
- [ ]  org.apache.shenyu.admin.service.impl.SelectorServiceImpl(46%)
- [ ]  org.apache.shenyu.admin.service.impl.UpstreamCheckService(60%)
- [ ]  org.apache.shenyu.admin.service.impl.DashboardUserServiceImpl(66%)
- [ ]  org.apache.shenyu.admin.service.impl.RuleServiceImpl(75%)
- [ ]  org.apache.shenyu.admin.service.impl.MetaDataServiceImpl(81%)
- [ ]  org.apache.shenyu.admin.service.impl.PermissionServiceImpl(62%)

**Comment by 0x12FD16B** [comment]
@JooKS-me If any question you have met, you can make a discussion on this issue or dev mail subscribe.

**Comment by JooKS-me** [comment]
> @JooKS-me If any question you have met, you can make a discussion on this issue or dev mail subscribe.

Ok, thanks for reminding~

**Comment by ttttangzhen** [comment]
hi, I'd like to take these task: 

- [ ] org.apache.shenyu.admin.listener.http.HttpLongPollingDataChangedListener(7%)
- [ ] org.apache.shenyu.admin.listener.http.HttpLongPollingDataChangedListener.DataChangeTask(0%)
- [ ] org.apache.shenyu.admin.listener.http.HttpLongPollingDataChangedListener.LongPollingClient(0%)
- [ ] org.apache.shenyu.admin.listener.AbstractDataChangedListener(3%)
- [ ] org.apache.shenyu.admin.listener.ConfigDataCache(0%)
- [ ] org.apache.shenyu.admin.listener.zookeeper.HttpServiceDiscovery(7%)
- [ ] org.apache.shenyu.admin.exception.ExceptionHandlers(18%)
- [ ] org.apache.shenyu.admin.config.LdapConfiguration(0%)
- [ ] org.apache.shenyu.admin.config.DataSyncConfiguration(0%)
- [ ] org.apache.shenyu.admin.config.ConsulServerConfiguration(0%)
- [ ] org.apache.shenyu.admin.config.DataBaseConfiguration(0%)

**Comment by 0x12FD16B** [comment]
@ttttangzhen I have marked HttpLongPollingDataChangedListener reference classes's test coverage as your task, for welcome more developer to participant in shenyu,  other classes you mentioned can leaf for more developer.

**Comment by ttttangzhen** [comment]
> @ttttangzhen I have marked HttpLongPollingDataChangedListener reference classes's test coverage as your task, for welcome more developer to participant in shenyu, other classes you mentioned can leaf for more developer.

OK，thanks

**Comment by Technoboy-** [comment]
I can help to do the fourth part of the work.

**Comment by 0x12FD16B** [comment]
@Technoboy-  I have create another issue of this part task for you #1849 , plz comment that issue.

**Comment by Technoboy-** [comment]
> @Technoboy- I have create another issue of this part task for you #1849 , plz comment that issue.

Yes, I have commented. And please help to review #1855.

**Comment by haibo-duan** [comment]
hi ,please assign these task to me:
following classes test code coverage
org.apache.shenyu.admin.shiro.bean.StatelessAuthFilter(6%)
org.apache.shenyu.admin.shiro.bean.StatelessToken(0%)
org.apache.shenyu.admin.shiro.config.ShiroRealm(0%)
org.apache.shenyu.admin.disruptor.subscriber.URIRegisterExecutorSubscriber(12%)
org.apache.shenyu.admin.disruptor.subscriber.MetadataExecutorSubscriber(60%)
org.apache.shenyu.admin.aspect.DataPermissionAspect(8%)
