### ISSUE TITLE
shenyu-common module test coverage improvement

### ISSUE THREAD

**Issue by 0x12FD16B** [apache/incubator-shenyu#1827]
## Task

Writing junit test case to impove shenyu-common module test coverage. Each task has been marked the classes that should be appended test code, if not specify, there are current code test coverage at end of line of each class. We hope the code test coverage can be improved to 85% above (the key logic code to 95%).

Task List:

- [x] task1: impove the follow classes code test coverage
	org.apache.shenyu.common.healthcheck.HealthCheckTask(0%) @Technoboy-
- [ ] task2: impove the follow classes code test coverage @Banana1995 
	org.apache.shenyu.common.enums.RpcTypeEnum(0%)
	org.apache.shenyu.common.enums.RateLimitEnum(0%)
	org.apache.shenyu.common.enums.AdminPluginOperateEnum(0%)
	org.apache.shenyu.common.enums.AdminResourceEnum(0%)
	org.apache.shenyu.common.enums.PluginTypeEnum(0%)
	org.apache.shenyu.common.enums.WafEnum(0%)
	org.apache.shenyu.common.enums.ParamTypeEnum(line coverage 100%, key branch coverage missing 25%)
	org.apache.shenyu.common.enums.HttpMethodEnum(line coverage 100%, key branch coverage missing 25%)
- [ ] task3: impove the follow classes code test coverage @lahmXu 
	org.apache.shenyu.common.exception.SerializerException(0% )
	org.apache.shenyu.common.exception.ShenyuException(30%)
	org.apache.shenyu.common.exception.CommonErrorCode(0%)
- [x] task4: impove the follow classes code test coverage @ywj1352
	org.apache.shenyu.common.dto.MetaData(0%)
	org.apache.shenyu.common.dto.ConfigData(0%)
	org.apache.shenyu.common.dto.convert.rule.impl.ModifyResponseRuleHandle(0%)
	org.apache.shenyu.common.dto.convert.rule.impl.ContextMappingHandle(0%)
	org.apache.shenyu.common.dto.convert.rule.impl.ParamMappingHandle(0%)

Please read the [Contribution Guideline](https://shenyu.apache.org/community/contributor/) before submitting the PR

**Comment by ywj1352** [comment]
task4: impove the follow classes code test coverage  assign me

**Comment by Banana1995** [comment]
i wanna take task2,pls assign to me

**Comment by lahmXu** [comment]
i wanna take task3,pls assign to me

**Comment by hhj0719** [comment]
task1: impove the follow classes code test coverage assign to me

**Comment by yu199195** [comment]
Hi, 

You can reply to the communication on the mailing list ： 
https://lists.apache.org/thread.html/r5c090356c793ad0bd7ada2dd51a76451580a1d583033ed0e97a472ec%40%3Cdev.shenyu.apache.org%3E

**Comment by changanjennifer** [comment]
I wanna take task 4 or task 2,

**Comment by hhj0719** [comment]
Sorry, the company has added important tasks for the time being. There is no time to deal with them for the time being

**Comment by Technoboy-** [comment]
> Sorry, the company has added important tasks for the time being. There is no time to deal with them for the time being

Please assign to me, @yu199195 .

**Comment by yu199195** [comment]
@Technoboy-   thanks for help

**Comment by lahmXu** [comment]
I have finished the task3, please mark it @0x12FD16B
