### ISSUE TITLE
Remove the lombok package dependency.

### ISSUE THREAD

**Issue by HessTina-YuI** [apache/incubator-shenyu#1866]
## Task

Plan to remove the lombok package dependency.

there are module to remove lombok's annotations

- [x] shenyu-admin @KevinClair 
- [x] shenyu-bootstrap @javaChain
- [x] shenyu-client @JooKS-me
- [ ] shenyu-common @YXxy1002
- [x] shenyu-disruptor @lw1243925457 
- [x] shenyu-metrics @danielchenxs
- [x] shenyu-plugin @strawberry-crisis  
- [x] shenyu-protocol @lahmXu
- [x] shenyu-register-center @zhaiweij
- [x] shenyu-spi @ChoviWu
- [x] shenyu-sync-data-center @hongyiheng
- [x] shenyu-web @javaChain

If you want to take it, you can reply this email and reply issue.

One person, one module. First come first served, and I will mark first person in issue. 

I will finish it, to remove lombok in pom.xml and LICENSE.

Thanks.

Please read the [Contribution Guideline](https://shenyu.apache.org/community/contributor/) before submitting the PR

**Comment by KevinClair** [comment]
Take module `shenyu-admin`

**Comment by javaChain** [comment]
task module `shenyu-bootstrap`

**Comment by JooKS-me** [comment]
take module `shenyu-client`

**Comment by lw1243925457** [comment]
shenyu-disruptor

**Comment by strawberry-crisis** [comment]
pls assign the "shenyu-plugin" part to me

**Comment by hongyiheng** [comment]
take module `shenyu-sync-data-center`

**Comment by javaChain** [comment]
take module `shenyu-web`

**Comment by zhaiweij** [comment]
take module shenyu-register-cente

**Comment by ChoviWu** [comment]
take module shenyu-spi

**Comment by lahmXu** [comment]
take module shenyu-protocol

**Comment by danielchenxs** [comment]
take module shenyu-metrics

**Comment by HessTina-YuI** [comment]
Thanks everyone. This task is over.
