### ISSUE TITLE
Optimize Exception printing in unit test

### ISSUE THREAD

**Issue by ttttangzhen** [apache/incubator-shenyu#1930]
## Task
Replace exception printing to exception annotation and assert

Module List:
- [x] shenyu-admin @ttttangzhen 
- [x] shenyu-agent @ttttangzhen 
- [x] shenyu-bootstrap @ttttangzhen 
- [x] shenyu-client @ttttangzhen 
- [x] shenyu-common @ttttangzhen 
- [x] shenyu-disruptor @ttttangzhen 
- [x] shenyu-examples @ttttangzhen 
- [x] shenyu-web @ttttangzhen 
- [x] shenyu-metrics @zhaiweij 
- [x] shenyu-plugin @zhaiweij 
- [x] shenyu-protocol @zhaiweij 
- [x] shenyu-register-center @zhaiweij 
- [ ] shenyu-spi @zhaiweij 
- [ ] shenyu-spring-boot-starter @zhaiweij 
- [ ] shenyu-sync-data-center @zhaiweij 

Please read the [Contribution Guideline](https://shenyu.apache.org/community/contributor/) before submitting the PR
