### ISSUE TITLE
[Task] <Optimize Sql file> Optimize Sql file for Plugin-handle,shenyu-dict for h2、mysql、pg

### ISSUE THREAD

**Issue by nuo-promise** [apache/incubator-shenyu#2412]
### Description

Optimize Sql file for Plugin-handle,shenyu-dict for h2、mysql、pg.

### Task List
- [x]  Optimize plugin-handle table for  h2 @nuo-promise 
- [x] Optimize plugin-handle table for  mysql @nuo-promise 
- [x] Optimize plugin-handle table for  pg @ShawnJim 
- [x] Optimize shenyu-dict table for  h2 @nuo-promise 
- [x] Optimize shenyu-dict table for  mysql @nuo-promise 
- [x] Optimize shenyu-dict table for  pg @ShawnJim

**Comment by AhahaGe** [comment]
is this issue need someone to fix it?

**Comment by nuo-promise** [comment]
> is this issue need someone to fix it, if yes can assign to me

You can work with me to modify the shenyu-dashboard？

**Comment by AhahaGe** [comment]
You can work with me to modify the shenyu-dashboard? Yes.

**Comment by nuo-promise** [comment]
> You can work with me to modify the shenyu-dashboard? @nuo-promise Yes.

The solution has now been changed, and no need to modify the dashboard.

**Comment by nuo-promise** [comment]
h2,mysql complete!

**Comment by AhahaGe** [comment]
> > You can work with me to modify the shenyu-dashboard? @nuo-promise Yes.
> 
> The solution has now been changed, and no need to modify the dashboard.

got it.

**Comment by ShawnJim** [comment]
i will complete pg.
