### ISSUE TITLE
[Task] <Add permission for admin backend> add permission for admin backend api

### ISSUE THREAD

**Issue by nuo-promise** [apache/incubator-shenyu#2517]
### Description

add permission for admin backend curd api.

### Task List

- [ ] modify shiro.
- [ ] add permission for AppAuth module.
- [ ] add permission for Config module.
- [ ] add permission for DashboardUser module.
- [ ] add permission for DataPermission module.
- [ ] add permission for Index module.
- [ ] add permission for MetaData module.
- [ ] add permission for Permission module.
- [ ] add permission for platform module.
- [ ] add permission for Plugin module.
- [ ] add permission for PluginHandle module.
- [ ] add permission for Resource module.
- [ ] add permission for Role module.
- [ ] add permission for Rule module.
- [ ] add permission for Selector module.
- [ ] add permission for ShenyuDict module.

**Comment by plutokaito** [comment]
please assign to me

**Comment by nuo-promise** [comment]
> please assign to me

ok
