### ISSUE TITLE
[Task] Add integration test for more http api

### ISSUE THREAD

**Issue by JooKS-me** [apache/incubator-shenyu#2679]
### Description

Hi community,

In `DividePluginTest`, there is only `/order/save` is covered. But we should test all http api in `shenyu-examples-http`. So we need to do the following task.

If you want to participate, please leave a message under issue.

### Task List

- [x] add integration test for http api in `HttpTestController` @totalo 
- [x] add integration test for http api in `OrderController` @totalo 
- [x] add integration test for http api in `RequestController` @gaochuang98 
- [x] add integration test for http api in `ShenyuClientPathController` @gaochuang98 
- [x] add integration test for http api in `SpringMvcMappingPathController` @QinHaiqi 
- [x] Add an controller related to file upload and download in `shenyu-examples-http`, and add integration test @QinHaiqi 

The integration test is expected to add in `shenyu-integrated-test-http`, and you can new a test class in `org.apache.shenyu.integrated.test.http` while doing integrated test.

**Comment by QinHaiqi** [comment]
give me a chance

**Comment by QinHaiqi** [comment]
give me a chance SpringMvcMappingPathController and shenyu-examples-http

**Comment by JooKS-me** [comment]
> give me a chance SpringMvcMappingPathController and shenyu-examples-http

good luck~

**Comment by QinHaiqi** [comment]
let me try **SpringMvcMappingPathController** and  **shenyu-examples-http**

**Comment by totalo** [comment]
I want to try `HttpTestController` and `OrderController`

**Comment by gaochuang98** [comment]
give me a chance ShenyuClientPathController and RequestController

**Comment by JooKS-me** [comment]
@totalo @gaochuang98 Thanks for help

**Comment by AhahaGe** [comment]
please assgin me dubbo example project
