### ISSUE TITLE
[Task] Add integration test for more dubbo api

### ISSUE THREAD

**Issue by JooKS-me** [apache/incubator-shenyu#2680]
### Description

Hi community,

In integrated test of `alibaba-dubbo` or `apache-dubbo`, there is only `/findById` is covered. But we should test all dubbo api in examples. So we need to do the following task.

If you want to participate, please leave a message under issue.

### Task List

- [x] add integrated test for `DubboTestService` in `shenyu-examples-apache-dubbo-service`
- [x] add integrated test for `DubboMultiParamService` in `shenyu-examples-apache-dubbo-service`
- [x] add integrated test for `DubboTestService` in `shenyu-examples-alibaba-dubbo-service`
- [x] add integrated test for `DubboMultiParamService` in `shenyu-examples-alibaba-dubbo-service`

The integration test is expected to add in `shenyu-integration-test-alibaba-dubbo` or `shenyu-integration-test-apache-dubbo`, and you can new a test class while doing integrated test.

**Comment by AhahaGe** [comment]
please assign these to me

**Comment by AhahaGe** [comment]
add integrated test for DubboTestService in shenyu-examples-apache-dubbo-service
 add integrated test for DubboTestService in shenyu-examples-alibaba-dubbo-service
the other two have some problem, I am writing this
