### ISSUE TITLE
[Task] <ShenYu Agent Task>

### ISSUE THREAD

**Issue by yu199195** [apache/incubator-shenyu#2699]
### Description

Hi Community

The upcoming 2.4.2 release will include the shenyu-agent, 
shenyu-agent contains mainly tracing observability features.
so there are still the following features to be completed.

### Task List

- [x] Add shenyu-agent document (Architecture and Usage)  @yu199195 
- [x] Add agent startup in the deployment document （docker 、linux） @JooKS-me 
- [x] Add Tracing-Jaeger document and integration test @HessTina-YuI 
- [x] Add Tracing-opentelemetry document and integration test @JooKS-me 
- [x] Add Tracing-Zipkin plugin and document , integration test  @midnight2104

**Comment by JooKS-me** [comment]
Hi, I can help to Add Tracing-opentelemetry document and integration test.

**Comment by HessTina-YuI** [comment]
I can add Tracing-Jaeger document and integration test

**Comment by yangtianrui95** [comment]
I can add Tracing-Zipkin plugin and document , integration test

**Comment by midnight2104** [comment]
I can add Tracing-Zipkin document and integration test.

**Comment by midnight2104** [comment]
I can add Tracing-Zipkin document and integration test.

**Comment by yangtianrui95** [comment]
@midnight2104 You do it first，please assign

**Comment by lxl910128** [comment]
hi gays, When I finish integration test for zipkin-plugin, I found that test for  jaeger plugin is not difficult. so I finish that, pls check it ~

**Comment by yu199195** [comment]
> hi gays, When I finish integration test for zipkin-plugin, I found that test for jaeger plugin is not difficult. so I finish that, pls check it ~

good job~
