### ISSUE TITLE
[Task] Update junit4 to junit5

### ISSUE THREAD

**Issue by haibo-duan** [apache/incubator-shenyu#2830]
### Description

 As we know,  JUnit 5 has been updated recently, which is more powerful and flexible to the JUnit framework. In ShenYu project,our unit testing framework is based on JUnit4，This task will migrating the unit testing framework from JUnit4 to JUnit5.

### Task List

- [x] pom.xml  @haibo-duan 
- [x] shenyu-admin @haibo-duan 
- [x] shenyu-agent  @hgaol
- [x] shenyu-client @hgaol
- [x] shenyu-common @hgaol
- [x] shenyu-integrated-test @lxl910128 
- [x] shenyu-loadbalancer @hgaol
- [x] shenyu-metrics @hbyandy
- [x] shenyu-plugin @haibo-duan 
- [x] shenyu-protocol  @haibo-duan 
- [x] shenyu-register-center @haibo-duan 
- [x] shenyu-spi @haibo-duan 
- [x] shenyu-spring-boot-starter @lxl910128 
- [x] shenyu-sync-data-center  @haibo-duan 
- [x] shenyu-web @haibo-duan

**Comment by hgaol** [comment]
I can try with `shenyu-common`, thanks!

**Comment by hgaol** [comment]
Hi there, this is my first PR and need maintainers to approve the workflows. Could anyone help me on that? Thanks! #2841

**Comment by haibo-duan** [comment]
@[hgaol](https://github.com/hgaol) Ok, thank you for your help .

**Comment by hgaol** [comment]
Hi @haibo-duan , thank you for your approval! I can also update the `client`, `agent`, `loadbalancer` modules.
Because `disruptor` and `bootstrap` has no test currently, I think there is no need to do the migration. Also please let me know if any other modules I can help.
After the change of root `pom.xml` has been merged, I can remove the dependencies in the sub-modules.

**Comment by lxl910128** [comment]
let me try shenyu-integrated-test

**Comment by lxl910128** [comment]
shenyu-examples using 'spring-boot-starter-test' which is using Junit 4 now.
should we change to junit 5 too?

**Comment by haibo-duan** [comment]
> let me try shenyu-integrated-test

OK ,thaks.

**Comment by haibo-duan** [comment]
I have assign these tasks to you. @lxl910128  @hgaol

**Comment by hbyandy** [comment]
let me try shenyu-metrics

**Comment by yu199195** [comment]
@hbyandy 

hi, thanks , shenyu-metrics will be remove by this version, you can choose other module~

**Comment by hbyandy** [comment]
let me try shenyu-plugin @haibo-duan

**Comment by haibo-duan** [comment]
> let me try shenyu-plugin @haibo-duan

OK,thaks your help.
