### ISSUE TITLE
[Task] Remove shenyu agent

### ISSUE THREAD

**Issue by yu199195** [apache/incubator-shenyu#3085]
### Description

We discussed in the meeting to remove the agent module. (https://lists.apache.org/thread/ow8o0hkym6p72gsoxxk0pyk895yk4wzv)

Logging and Metrics we use shenyu's plugin system to do.

About tracing, Encourage developers to provide plugins to upstream like SkyWalking, ZipKin and OpenTelemetry to implement the tracing features.

### Task List

- [x] new shenyu metrics plugin
- [x] new shenyu logging rocketMQ plugin
- [x] remove shenyu agent
