### ISSUE TITLE
[Volunteer] format  SQL to improve code readability in shenyu-admin.

### ISSUE THREAD

**Issue by midnight2104** [apache/incubator-shenyu#3088]
### Description

Hi Community:
This PR is to format the current SQL, following the principle of right-aligning keywords (Uppercase) and left-aligning fields. I would like to make this task a good first issue so that new comers can get involved in handling the rest of the SQL file. Do you think it's a good idea?

for example:
before formatting:

```SQL
select id, name, age from user where id = 1
```

after formatting

```SQL
  SELECT id, 
         name, 
         age 
    FROM user
   WHERE id = 1
```

### Task List

- [x] 1. app-auth-sqlmap.xml @midnight2104 
- [x] 2. auth-param-sqlmap.xml @hutaishi
- [x] 3. auth-path-sqlmap.xml @[ShawnSiao](https://github.com/ShawnSiao)
- [x] 4. dashboard-user-sqlmap.xml @[Jingwugate](https://github.com/Jingwugate)
- [x] 5. data-permission-sqlmap.xml @[Mayank-KS](https://github.com/Mayank-KS)
- [x] 6. meta-data-sqlmap.xml @[selectbook](https://github.com/selectbook)
- [x] 7. permission-sqlmap.xml @[wklong](https://github.com/wklong)
- [x] 8. plugin-handle-sqlmap.xml [joker-zxs](https://github.com/joker-zxs)
- [x] 9. plugin-sqlmap.xml  @[zhangcly](https://github.com/zhangcly)
- [x] 10. resouce-sqlmap.xml @[nydia](https://github.com/nydia)
- [x] 11. role-sqlmap.xml @Albertsirius
- [x] 12. rule-condition-sqlmap.xml  @UniverseInHeart
- [x] 13. rule-sqlmap.xml @totalo
- [x] 14. selector-condition-sqlmap.xml @lanseBlue
- [x] 15. selector-sqlmap.xml @xiaheshun
- [x] 16. shenyu-dict-sqlmap.xml @shallwetalkge
- [x] 17. user-role-sqlmap.xml @erdengk 

Notice: input `about issue 3088` in your pr desc .

**Comment by hutaishi** [comment]
Can you randomly assign one of them to me? Thank you very much.

**Comment by midnight2104** [comment]
> Can you randomly assign one of them to me? Thank you very much.

thks for your contribution

**Comment by xiaheshun** [comment]
Can you randomly assign one of them to me?

**Comment by midnight2104** [comment]
> Can you randomly assign one of them to me?

doen,  15. selector-sqlmap.xml

**Comment by totalo** [comment]
Can you randomly assign one of them to me? Thank you.

**Comment by midnight2104** [comment]
> can you assign 14. selector-condition-sqlmap.xml to me thank you

Thks for your contribution.I'm looking forward to you PR. Please contact me with any questions you may have.

**Comment by UniverseInHeart** [comment]
can you give me one not be format? thanks

**Comment by Albertsirius** [comment]
Can you assign one of files not formatted to me? thanks.

**Comment by midnight2104** [comment]
> Can you assign one of files not formatted to me? thanks.

`11. role-sqlmap.xml` for you, I'm looking forward to your PR.

**Comment by midnight2104** [comment]
> Can you assign one of files not formatted to me? thanks.

you can do  `12. rule-condition-sqlmap.xml `

**Comment by zhangcly** [comment]
Can you assign one of files not formatted to me? thanks.

**Comment by nydia** [comment]
Can you assign one of files not formatted to me? thanks.

**Comment by wklong** [comment]
hi, can you assign 7. permission-sqlmap.xml to me,thank you

**Comment by haibo-duan** [comment]
> hi, can you assign 7. permission-sqlmap.xml to me,thank you

yes,now you can do 7. permission-sqlmap.xml

**Comment by haibo-duan** [comment]
> Can you assign one of files not formatted to me? thanks.

9. plugin-sqlmap.xml  for you . @[zhangcly](https://github.com/zhangcly)

**Comment by haibo-duan** [comment]
> Can you assign one of files not formatted to me? thanks.

10. resouce-sqlmap.xml for you. @[nydia](https://github.com/nydia)

**Comment by selectbook** [comment]
hi, can you assign 6.meta-data-sqlmap.xml to me,thank you

**Comment by midnight2104** [comment]
> hi, can you assign 6.meta-data-sqlmap.xml to me,thank you

yes, looking forward to your PR.

**Comment by ShawnSiao** [comment]
Can you randomly assign one of them to me? Thank you very much.

**Comment by midnight2104** [comment]
> Can you randomly assign one of them to me? Thank you very much.

yes, you can do 3. auth-path-sqlmap.xml

**Comment by ShawnSiao** [comment]
您好，邮件已收到。

**Comment by Jingwugate** [comment]
Can you assign one of files not formatted to me? thanks.

**Comment by Jingwugate** [comment]
There are three unassigned tasks，Can you assign one to me？thank you

**Comment by midnight2104** [comment]
> There are three unassigned tasks，Can you assign one to me？thank you

yes. you can do 4. dashboard-user-sqlmap.xml

**Comment by joker-zxs** [comment]
good

**Comment by joker-zxs** [comment]
Can you randomly assign one of them to me? Thank you very much.

**Comment by Mayank-KS** [comment]
There are two unassigned tasks, can you assign one to me? Thank you

**Comment by midnight2104** [comment]
> Can you randomly assign one of them to me? Thank you very much.

8. plugin-handle-sqlmap.xml

**Comment by midnight2104** [comment]
> * data-permission-sqlmap.xml

 data-permission-sqlmap.xml

**Comment by chineseGo8341** [comment]
> 

have you finished the task assigned to you yet?plz let me know, I want to commit too

**Comment by midnight2104** [comment]
> > 
> 
> have you finished the task assigned to you yet?plz let me know, I want to commit too

This has been done, there are more newcomer tasks later, stay tuned.

**Comment by midnight2104** [comment]
> Can you randomly assign one of them to me? Thank you very much.

hi, what's your progress? do you need help?

**Comment by joker-zxs** [comment]
Wait a minute. I won't have time until tomorrow





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/incubator-shenyu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月9日(星期六) 晚上8:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/incubator-shenyu] [Volunteer] format  SQL to improve code readability in shenyu-admin. (Issue #3088)





  
Can you randomly assign one of them to me? Thank you very much.
  
hi, what's your progress? do you need help?

**Comment by midnight2104** [comment]
done

**Comment by ShawnSiao** [comment]
您好，邮件已收到。
