### ISSUE TITLE
[Task] downgrade curator version to 4.x to compatible with some plugin like sofa

### ISSUE THREAD

**Issue by hgaol** [apache/incubator-shenyu#3556]
### Description

some details can refer to #3461 .

Due to the Curator version incompatible issue in bootstrap. I plan to downgrade to version 4.0.1, because this version has been tested works well for sofa/dubbo/motan/tars. Please let me know if any comment.

### Task List

- [x] quick fix: adding back curator dep in bootstrap
- [x] bootstrap-instance
- [x] bootstrap-data-sync
- [x] admin-register
- [x] admin-data-sync
- [x] client-register
- [x] clean `pom`s
- [x] LICENSE files

**Comment by hgaol** [comment]
Considering Curator version 4.3
